### ISSUE TITLE
Numbers has to accept unlimited numbers, not an "n"

### ISSUE THREAD

**Issue by extsoft** [posypaylo1/pbc-posypaylo#5]
https://github.com/posypaylo1/pbc-posypaylo/blob/adaf799040bb568c6aa8ad73f3ca00d01c348a6f/numbers_pairs.py#L3

Requirements: https://gist.github.com/extsoft/bf1b9884cbaccf1eb2efd0330ae542c7#3-numbers-pairs

**Comment by posypaylo1** [comment]
fixed
