### ISSUE TITLE
Incorrect log format

### ISSUE THREAD

**Issue by extsoft** [posypaylo1/pbc-posypaylo#8]
https://github.com/posypaylo1/pbc-posypaylo/blob/fd739c55e8c7264ed846d1d0ee17755c74b030a6/my_tested_app/log_decorator.py#L4

Visit https://gist.github.com/extsoft/f9963e86d9162604fe2d012b0653d7d0#5-decorator for details.

**Comment by posypaylo1** [comment]
fixed
